### ISSUE TITLE
Translations broken in the 3rd November 2024 iso

### ISSUE THREAD

**Issue by bittin** [agama-project/agama#1724] opened 2024-11-04 06:49 UTC
Hey!

testing with https://download.opensuse.org/repositories/systemsmanagement:/Agama:/Devel/images/iso/agama-installer.x86_64-10.0.0-openSUSE-Build25.171.iso today as i promised to do some more testing today

if you change to another language it does not get applied and you still get English only

**Comment by dgdavid** [comment] 2024-11-04 08:21
Are you able to collect the logs? Asking because... it works for me :roll_eyes:

**Comment by dgdavid** [comment] 2024-11-04 08:21
> it works for me 🙄

At least changing from English to Español.

**Comment by bittin** [comment] 2024-11-04 08:26
> Are you able to collect the logs? Asking because... it works for me 🙄

here comes the logs: https://webb.marisa.nu/agama-logs.tar.gz

**Comment by imobachgs** [comment] 2024-11-05 11:45
I can reproduce the problem in the product selection page. If you reload, the UI will be already translated, but it should happen automatically.

**Comment by bittin** [comment] 2024-11-06 00:39
alright, this is still a problem in the 5th November iso: https://download.opensuse.org/repositories/systemsmanagement:/Agama:/Devel/images/iso/agama-installer.x86_64-10.0.0-openSUSE-Build26.4.iso

**Comment by imobachgs** [comment] 2024-11-06 06:23
> alright, this is still a problem in the 5th November iso: https://download.opensuse.org/repositories/systemsmanagement:/Agama:/Devel/images/iso/agama-installer.x86_64-10.0.0-openSUSE-Build26.4.iso

Yes, we can reproduce the problem, but we have yet to work on it.

**Comment by bittin** [comment] 2024-11-06 09:31
> > alright, this is still a problem in the 5th November iso: https://download.opensuse.org/repositories/systemsmanagement:/Agama:/Devel/images/iso/agama-installer.x86_64-10.0.0-openSUSE-Build26.4.iso
> 
> Yes, we can reproduce the problem, but we have yet to work on it.

Alright i see, will test again on Friday or next week when i have time 

sick with migrane, fever and cold at the moment

**Comment by imobachgs** [comment] 2024-11-06 11:14
Take care! We will update the bug report when the problem is fixed, and we do not expect it to happen this week.

**Comment by bittin** [comment] 2024-11-06 11:28
> Take care! We will update the bug report when the problem is fixed, and we do not expect it to happen this week.

Alright then i know

**Comment by bittin** [comment] 2024-11-13 08:01
Still not fixed with the 12th November iso: https://download.opensuse.org/repositories/systemsmanagement:/Agama:/Devel/images/iso/agama-installer.x86_64-10.0.0-openSUSE-Build28.5.iso

feel free to ping me when this is fixed so i can test again

**Comment by imobachgs** [comment] 2024-11-13 08:54
We are working on this (and other translation problems). We will update the issue when is done.

**Comment by bittin** [comment] 2024-11-13 08:56
> We are working on this (and other translation problems). We will update the issue when is done.

Alright thx

**Comment by imobachgs** [comment] 2024-11-14 07:01
Fixed with #1746.

**Closed by imobachgs** 2024-11-14 07:01 UTC
Labels: bug

**Comment by bittin** [comment] 2024-11-14 07:08
> Fixed with #1746.

cool will test next week then, pretty busy rest of this week, still sick and family coming over as i turn 34 on Sunday

**Comment by bittin** [comment] 2024-11-16 07:59
Works as it should now, had time to test this morning with the 15th November iso: https://download.opensuse.org/repositories/systemsmanagement:/Agama:/Devel/images/iso/agama-installer.x86_64-10.0.0-openSUSE-Build30.16.iso
