### ISSUE TITLE
s390x installation can't be finished

### ISSUE THREAD

**Issue by mmaslano** [agama-project/agama#1818] opened 2024-12-06 14:42 UTC
I tried to install agama-installer.s390x-10.0.0-SLE-Alpha2.iso, which failed to boot after the installation. But it was possible to pick dasd disk, activate, format and storage management was happy. I didn't setup partitions and used default.

With agama-installer.s390x-10.0.0-SLE-Build38.1.iso I'm unable to finish the installation because of the storage. I activated dasd, formatted, but I still see "Storage proposal not possible". I disabled btrfs snapshots, sadly I was unable to change partitions fs from btrfs to xfs for /. It looks like it's not possible to delete / and start over and edit doesn't help.

I'm attaching logs, but I doubt it's helpful. Maybe the right button is there, but I can't find it, which will be also a problem for customers. 

[agama-logs-1733517061.tar.gz](https://github.com/user-attachments/files/18039492/agama-logs-1733517061.tar.gz)

**Comment by kobliha** [comment] 2024-12-06 15:17
Maybe related to #1758

**Comment by ancorgs** [comment] 2024-12-09 08:52
The problem has nothing to do with Btrfs vs XFS or with enabling/disabling snapshots.

Storage cannot make a proposal because there is no disk considered as a valid candidate. I will investigate why.

**Comment by ancorgs** [comment] 2024-12-09 08:59
Reading the logs...

After activating the DASD, a so-called storage reprobing is performed and dasda is considered as an acceptable disk:

> y2storage/disk_analyzer.rb(candidate_disks):142 Found candidate disks: [<Dasd /dev/dasda 21600000 KiB (20.60 GiB)>]

But then Agama makes a new proposal and seems to ignore that disk for some reason I would need to investigate:

> y2storage/guided_proposal.rb(try_with_target):179 Trying to make a proposal
> using the following settings:
>    root_device: 
>    candidate_devices: [""]

**Comment by ancorgs** [comment] 2024-12-09 11:27
@mmaslano Gave me access to the machine and I reproduced the bug. The problem is that, after performing the DASD operations, Agama tries to update the list of installation issues. But that process is failing because `storage_manager.proposal` is nil when this line is executed:

https://github.com/agama-project/agama/blob/master/service/lib/agama/storage/proposal_strategies/guided.rb#L65

Everything goes downhill from there.

I will commit a fix.

**Comment by ancorgs** [comment] 2024-12-09 14:42
#1822 implements a workaround. The root of the issue is not fixed, but the failing code path will disappear in a couple of months when the new storage proposal is finished.

I will keep the issue open to make sure we test this scenario with the new storage proposal.

**Comment by ancorgs** [comment] 2024-12-09 14:53
Trello card (private SUSE link): https://trello.com/c/hv9UCWm0/726-s390x-installation-cannot-be-finished

**Comment by ancorgs** [comment] 2024-12-19 10:54
Fixed by the mentioned workaround #1822

**Closed by ancorgs** 2024-12-19 10:54 UTC
