### ISSUE TITLE
Agama 10 doesn't show Slowroll

### ISSUE THREAD

**Issue by WesfunOfficial** [agama-project/agama#1697] opened 2024-10-25 02:03 UTC
Hello, I recently added the .yaml files to Agama and they were merged but I am not seeing it as an option in Agama 10, any maintainers know the reason?

**Comment by WesfunOfficial** [comment] 2024-10-25 02:08
it just occurred to me that the change may not appear until Agama 11 but I don't have any indication that its the case

**Comment by imobachgs** [comment] 2024-10-28 09:46
Thanks for your report!

The problem is that an [invalid date](https://github.com/agama-project/agama/blob/b1e266b52c1111092da9fb7fcf3ac236aa21c002/products.d/agama-products.changes#L9) in the changes file prevented the submission of your changes.

It should be fixed by #1703 and Slowroll should be available today in the [Agama 10 ISO](https://agama-project.github.io/download).

**Closed by imobachgs** 2024-10-28 09:46 UTC
